### ISSUE TITLE
How to reproduce preprocessed Tanks and Temples?

### ISSUE THREAD

**Issue by t2kasa** [FangjinhuaWang/PatchmatchNet#20]
Hi,

I would like to know how to reproduce preprocessed Tanks and Temples.
Especially my question is: how did you obtain the last line of `cam.txt` files?

For example, [MVSNet](https://github.com/YoYo000/MVSNet) also provides preprocessed Tanks and Temples. The camera parameters of the first image for `Auditorium` scene in advanced set are:
```
extrinsic
0.999749 0.0222156 -0.00306238 0.0954387
-0.0223105 0.999119 -0.0355459 -0.0991731
0.00227 0.0356053 0.999363 1.04493
0.0 0.0 0.0 1.0

intrinsic
1162.86 0 963.831
0 1162.86 541.647
0 0 1

0.367867 0.00391897 730 3.22871
```

And your providing camera parameters of the first image for `Auditorium` scene are:
```
extrinsic
0.999749 0.0222156 -0.00306238 0.0954387 
-0.0223105 0.999119 -0.0355459 -0.0991731 
0.00227 0.0356053 0.999363 1.04493 
0.0 0.0 0.0 1.0 

intrinsic
1162.86 0.0 963.831 
0.0 1162.86 541.647 
0.0 0.0 1.0 

0.367867 6.127867
```

As you explained in [README](https://github.com/FangjinhuaWang/PatchmatchNet#reproducing-results), the fist value of the last line is `DEPTH_MIN`. So I know the value `DEPTH_MIN` should be same. But the second value of the last line is `DEPTH_MAX`, which corresponds to the fourth value in the last line in MVSNet, and different value.

Could you tell me how to obtain the values or how to reproduce the preprocessed Tanks and Temples?

I look forward to hearing from you.

**Comment by FangjinhuaWang** [comment]
Hi,

Tanks & Temples is a special dataset since the ground truth point clouds are processed and do not include background. E.g. ground truth point cloud of Family scan only includes the statue but does not include chairs and distant buildings. So that's why MVSNet provides a file named "short_range_camera_for_mvsnet.zip" for intermediate dataset to decrease the depth range compared to the original one generated from COLMAP. With a small depth range, the background can be filtered out during reconstruction. 

In our case, based on the camera files from MVSNet, we do some hand tuning in experiments to remove the background pixels. To reproduce results, you can just use the dataset that we uploaded. 

For ETH3D dataset, the ground truth point clouds are directly obtained using a high-precision laser scanner, including distant background. So we directly use the depth range based on the sparse reconstruction from COLMAP and do not do any hand tuning.

**Comment by t2kasa** [comment]
Thank you very much for your detailed answer!
