### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'detach'

### ISSUE THREAD

**Issue by cainsmile** [FangjinhuaWang/PatchmatchNet#67]
When I try to run "eval.sh", the question in the title occurred. Do you know how to figure it out? Appreciate for your help.

**Comment by cainsmile** [comment]
Hi, I figure it out, although I don't know how. But another question occurs. The program has generated .ply files, but there is no point cloud in the files, and the program reported no errors. The pretrained model is module_000007.pt which you offered, and the testing dataset is DTU. The only change I made was to delete "--parallel" in eval.sh and the dataset path. My guess is that the problem is with **depth initialization**, but I couldn't find a solution. Thanks for your help again.

**Comment by FangjinhuaWang** [comment]
Hi,

I am not very sure where the problem is. Seems that the estimated depth is noisy and totally filtered out during post-processing, e.g. geometric consistency filtering. The current version of codes can be used to successfully reproduce similar results on DTU. Did you use the DTU test dataset that we provide?
